language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: AIh8xwHMvcUWD49Jgv4AopaeK4r24HFjoLcPm5MF8jZ7gd5E+G89/46Mq98RrxonO5f6tobEG/cBqcZC9pVfbrD4l2ZeV1loAvN7zxBIYHC9Lfrje20GOhCjgH0dQ7RoW67OfLzxFvkTRE+hMiwsFpMSPJfsPJ2HveqM5Anan5J+xYv+tf8OgFk6o9hOqeceQ4xjMECAjT8VkugquL6Wv4g3MF8tZ4SJqrlonAliJQ+PT/u0ny23d2CVxDMh5Gl6zEcimKLRdeKDKuRB6qAwFpU6LUyd7hMoaZYIeGR7+Z+gNVvRU85GzHcg0YotooVq2XYeIYjN+v/bTElfCA9fDPJ+Kf6ExYd3xNiMtVs047HYudrtDqDVuI0bGnnytB0abj4qHC96TIEBeKVzEZXU5qV5OhuCBM0SfTGkX+FRdeu4t/Qfe6f94KYWIpZbci8bKmK5rqX78350AKWMuYhLiYAV0snQjvoCThopsELviTXQYzQlSQ7b1UBzVxjkP+Xvrz1UCQ6M9YbQkQYXJhh9Rdy4pC7u3cAUnsO3c2MMg1WTqd8Wo5wHsNuOHhnHzx3BUr0vYyxkB371qJmkJvsCon81pK0P26fXsh+z4ONc7w1d/HkEXBkc3qSAH+6vn/y7j1DTKsHyFqSIhc39TZcDTmMocoE1SJiRGkafjlbxOeA=
  app: shelenkov
