language: java
dist: xenial
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: HetJQg+KGYAokLdSOLqDISVdQ0h928oI3TzokBhyeLidxKwBvgmKrqZ6LIsTbfku/OcIswJzY8SWzEXuQ9KuxprQrTgvBSxbwtRGWbp9cxgLvcJsNKstZhKO5aOgCo7QjSR99jrS/R5pXXcujUu1NDuYH0z7g/ZNfdCVwNG+AANYPf/6w5sYJRc0eCfEmldBsTTyS6eZmDDou5TArOM9g58TiwlNiqcgSw7hKCF7XPjj/Z0YLzIYXRtpKOYg8ceRXlJaBhliNsucrQcMxD7JMxCowN2VETHoSVh/D77obo/Wf2Vz+4GvaMbevbNyKewjn+MufSmyD5h79BtUSp3kTnqugbOvc/UyM9rRBqzK5S7PhT6mPVQ9FB73WyOwhG/+hF0rlp0lTHHHs8X6slC3z8cHJaZBeDgZQdHPezpcDdPhgymdsK7j3Rq0aoeFupWlG7Ai1bNVIiP0PqPBOadz9VGMKbSARFE0JXfwmHx/p95N1pKZrCnRsZIxDg1jprpe9Xou2zmCh4u4FP8ncVKgGF5jgoANHHj4T2zKWauWOzZO14IZUrF/imLQBJ20BE6T5UeP32hLAs+M1WTVGSYrtmS6HoC3o+JP5sqDNzZu+TA7IWLtjHNYM4jl2BKC5hcfiy6fYq8SzNUgIUwZ4rdjtKt1GAsW9DuEghgdy6mePEM=
  app: shelenkov
