language: java
dist: xenial
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: CgnYAkBLmC0SKiPNDUFdWfyu8rTSAavNr7ZYYZKIudM3X8zc6QqiINvbD21COzjRZ/ieBkbDvxm5/y+2jwN1eLwbCgQv0VcckllCn+5F6H+mb27KQL+jXO6W/0tszFM3157/F+aLVnCiZfrajn9+bStVA8/yHqVQjvA5ZIM4y8u7gnyKsSwGDfbrugeNsEG/ozXr5OyCuXOPHMtcKnRnpkld2c1vV0d5vx8ki4w7u27Fm5qsp2YggL5ErnnH6qYI+0tuumLtlN9H3dxk5p45RWuXmoLIZL90q5s5w3uUCExNSwYx3oQQqQiJlg1mQg5T7e0iKvQcurj2aSHarivvllXOZJOH+ihv7s0OyqVd/WfNjroiQWPNcIEy6LD18e49Bt3v63XQpmoX7GjIV6YnYq5971WJxuA/zmFtdGba0TSFYU3qGaE4cm2WbIM3BCWvmmnvt3TPA9dt9Qygk0T8haoQ2yM8ETb/9W/RCmLMgbELZnxjHUFa73DYhiLGKObPLzzdjlpsm1YitbZPpilqn9no3DQY0HzDpGlbw9cNkJDSS3AkGgAO92NWe/UQyzHeAPaNUpgN+af9wl6U8QCOxjRyklkrdXmhlmAg3kUtfgaK0vDmlmD/e7JZgLvMealNFS7ynWWeEU9ybREVHv1kPAyrNbNwZKC4ZANgtQLlyhI=
  app: shelenkov
