language: java
dist: xenial
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: FJer54AzcSxmfj3nZNjmizv4u4EGLKAZUYezqbw50tPwmVL9wTQsGygQFiNAJjeuJ+tuxp8JiAXZ+98AwM1zjY1LYvG62Q0S1aTuFD3ILPzCnXxKhDjppX84PISQb8cPA8lyO+aX2auN7kab503DsIvL/okdZed0QdQrzG5ggP1Ob+0ZK1XZqdkHl1XJNAmnQjTipMfE/0yqClKdPCf2RVMUlUXq033i5B06uypnR3sD6WSneOD8tYvnnY+Fv6rS57QUF3d3C+7fLpO/5rKpCJAaCecPnWhq0KbvivFauFhLBWCVwtKR64KuQ7gWgT7SHA9OzoZnysgsWlF/hPJIw39PC2g1nOY2TDSJFovMnl5V8oy+6ziLn6lYEc5f/9Jpc1hA/403h5Gz3hGmGajHWcPvf9SpQ3rjfbJkqm/y8rvJiFhWubUqljiksaEUlnFk2ayz7gPlHFjz+kvpSp5pvouD1AoJbDkFDzUt9ECBAfayjyyTgxs/WbBc8HSQE64tPoApxuGHpiH6ECffp3X6UQgce6AlpZ1JMEjqMYGnwl9vIv1Efy2KUXnfsweCejsG2RRQn6/2guJbXyrBmeCHQNefTXIICpsvDEqf6R7STtifaP1HCXHpXoZkguNjTFIriq9lqznVrY7ZfbLQvjpFxJpAEJ11raAdXkQSCg2emWA=
  app: shelenkov
