language: java
dist: xenial
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: VZbQs4plMuCvrFVKlJ/Ia8b985xx397WNEZp+ERhzpeUFemBvJI3Bnsaj4NtEemz18aJJ04+GPsg5GKkg11yhb7ZZPX0ZNNAyW5Vng5KfVCMP2dGMor0qdTOlLLAQw2fSQ8Ku8CJcBewWHecKXg48K48MhB7blB2STWleqLvtGFExR3819SHIJCL5cZLYF8hbVvwSkHICWa01Bn3LEuGNDIpRBJzODNf1O2x+uSiCEMdYMkVuixOLpsUuufc8sPp+4p2pxU0d10mR9VtveWZsaNRhUSD9xCreT7TF4TY7ZIjZxXP3/gwgdcGSfrf/b4iGLZR/4BqxHGDly6fe0yP7YojP615TI874RwNBjT3QOt9roK91bdz5+L4xS0LQ6Xo4MJDoI0kxgVmqFeoeBX11A0R2CwqguQIWfSlxKIqxsFqBlB179GzKCo9R6lH2eyalU4cz+AmvX6Av2OKY3ZVP463esXkWJBUIqP6zC+0PFewJpfO/aJdIrtwXc4/VL1yZz61oXYyB1hkqzM9OwpZwDJibO9gzvK04OnRS3OxV/ssr8K+kUa+f3jFJsyTkQsQcAx67gyalD0OQ6HOImhJtf0CSY5CJsNY511y/Nu6gZZUM9nEreRnVqOWs0/OKJjevTSKOUwinvfp6quOVOFIK3mamTeupDc6DB3Z4tOVZOQ=
  app: shelenkov
