language: java
dist: xenial
jdk: openjdk8
services:
  - docker
cache:
  directories:
    - "$HOME/.m2"
script: ./mvnw verify -B
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure : D/AMBv7/wyecOHEGdduqlpSBVISRlApm+yHPngOwWtyu0ui/3Zf6CI9Ac4o6izAAVsJm2+hUVHVATqwwdWNV8TFAGsJpQbWTn1AhW2UpvAzH9j8SMiXWOAbNYkvRohB/UCIhSgaN49p8TBJD5KoKkSkgFIVOEDvTM+Mq+X+homvXCsBGVa92/iOBCUfY9HiqNXhKSrf3B3kp3AENTz5esxnnDdAJEaOWz5yhmEDHG7TyLyyooELng5HNmB0ImbxbOMGCmb66MGb3pLQgpes6sTBq6QcaGWYVosUm7cTXFByX+6JCsR+Uqe6QhQUSCqoG9BCnBYgMZZM41B8uOnUQFGqjBE6zsZ46sRYhQRywjvhRX+sluGfAxJ8IWCXTnJ61wCb7CAfBfjzCREQCKCxACOiw7D5rLtW+PirEDnBzTUGVOTuZ8IB6OpZLf4bbwdOGLLxqDlLlzKlADT7jOimKRlv9jDUVZzFKlQxgTnziHknUOAMp5EcieI+ssT6ffXAQTXxTyPuu4j0OPbNXQq78Zq3qI32w/Y7XT2oMr2cznc/n8bWbsUF72bKKAHa9bPTkB/3cOLxuYf/lDHfBWUKVV2OkpjlYMgQDagqumPRna5K0pYMimBLrDAQJp/Hr0IqiBAXYCkKt24vvyoh2Uv98LjYH2kZQ/6lKS36huNIzvTw=
  app: shelenkov
  edge : true
