language: java
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: Y2mrN7o2XoZ08/v7V163S55rArr3eL488m4uYXJ+LSdPX1EvYhol99S2oa+oGzG4xsQ3XhdllpHKMcsDdWq7OGqxB4J8SUCLUKpVgZoYXX3F5wZ2X4h8VWeYsBktlELyqWqo0MRpv4CqpSuZnYr1OwiYzbpD+RGRaRqLV0qCPvcXNTK+UBh70s9eRllXPUKsnMYitVmRIjtNBdDReXO6YMdYRSr+wZEXZi5M+ob5NJJCsEwZ9eh096KODBR/vO5F8tFfxbdmB9MhpJK/eqQGGb9tG9lDv9pDGF6Bq9T8LyzLh/BmVidYgZpjZW+6ZGvETK49RCNx/fnRZBcqcIifVG+H1XK81VdeyHV5xQCbOIDBfus93mHpFyWDDiUoSmvloNQ7eu2r+OdnuNVTmaV1ZE9cCmKnu03RO76TYxj12qTKH/cX2UE9UnFUj3QK8eElvdUPdpOwW3CUyCohbIPPD1WrYzdYxq+4jHSxvyi55mBlBoepWZEpLlvUD6RdUqx7OM0OSYAMJGQUXKZ63p0q4W3cg1ikrWykk/KFfscjew5juQQAkZXKm9nffOx2OjWIGtyTzHn202fW9D0ZDzdBRihXMoPd7CTafRwH0jyYPK7S0A3Q5OphLC+o5TCZa7XxX2c2CR5q5pkWmtzZCME3REXHqodRGq+M04l1J8KKCGU=
  app: shelenkov
